# Generated by Django 5.2 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#4285f4', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
